services:
  server:
    build:
      context: .
    # ONLY IN DEV
    # Don't need to mount WORKDIR in Production
    expose:
      - 3000
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - .env
    tty: true

  db:
    image: postgres:16
    restart: always
    user: postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    # Leave this as Documentation
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # Expose to Other Container
    expose:
      - 5432
    # Don't Set the Interval Too Long or Will Increase Build Time
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 5
volumes:
  # check out with docker volume inspect db-data
  db-data:
